project:
  type: website
  render:
    - "**/*.qmd"

website:
  favicon: img/wandrille.jpg
  title: "Wandrille DORCHIES"
  navbar:
    background: "#396E9E"
    left:
      - href: index.qmd
        text: Home
      - text: CV & Academic projects
        menu:
          - href: docs/academicprojects/CV.qmd
            text: "CV"
          - href: docs/academicprojects/ENSAI_projects.qmd
            text: "ENSAI projects"
          - href: docs/academicprojects/DUT_projects.qmd
            text: "DUT projects"
      - text: Personal Projects
        menu:
          - href: docs/personalprojects/datascience.qmd
            text: "Data Science"
          - href: docs/personalprojects/bballbaord.qmd
            text: "Basketball Dashboard"
          - href: docs/personalprojects/runningboard.qmd
            text: "Running Dashboard"
      - text: Hobbies
        menu:
          - href: docs/hobbies/sports.qmd
            text: "Sports"
          - href: docs/hobbies/other.qmd
            text: "Other"
    right:
      - href: docs/bookmarks.qmd
        text: Helpful Resources
      - icon: github
        href: https://github.com/WandrilleDorchies
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"}<br>
      [Source Code](https://github.com/WandrilleDorchies/WandrilleDorchies.github.io){.external target="_blank"}
  repo-url: https://github.com/WandrilleDorchies/WandrilleDorchies.github.io
  repo-branch: main
  reader-mode: true

format:
  html:
    theme:
      dark: cyborg
      light: cerulean
    css: styles.css
